source: docs
api: https://www.mapbox.com
url: https://www.mapbox.com
permalink: /:categories/:title
baseurl: /mapbox-android-sdk
pygments: true
version: v0.2.3
defaultid: 'examples.map-i86nkdio'
rdiscount:
  extensions: [smart]
